### ISSUE TITLE
Installing Scoop in Windows automated script

### ISSUE THREAD

**Issue by jahanbani** [jdhao/nvim-config#117]
1. When installing using the Windows automated script, scoop cannot be installed since the installation using elevated terminal is turned off by default by scoop. Please see: https://github.com/ScoopInstaller/Install#for-admin

This seems to be a better solution:
`iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
`
2. I already had 7zip installed, so scoop threw an error. Maybe we should check if 7zip is already installed (if installed update 7zip)
3. There is a folder location in the automated script (D:/portable_tools) that may throw an error if partition D is not available, maybe an address in the $HOME would work better.
4. I think the last line of the automated script should be:
`scoop install neovim-nightly`
since the comment above it talks about the nightly version
5. would it be possible to install Packer and your config in the script so everything is installed in one go?

**Comment by jdhao** [comment]
Thanks for the comment!

> When installing using the Windows automated script, scoop cannot be installed since the installation using elevated terminal is turned off by default by scoop

I have not tested this, but I think [this line](https://github.com/jdhao/nvim-config/blob/master/docs/nvim_setup_windows.ps1#L2) is used to bypass the scoop install issue.

> 2. I already had 7zip installed, so scoop threw an error. Maybe we should check if 7zip is already installed (if installed update 7zip)

Yeah, definitely,  I am not good at write powershell script and the script is not complete for all cases. You can create a PR for this?

> 3. There is a folder location in the automated script (D:/portable_tools) that may throw an error if partition D is not available, maybe an address in the $HOME would work better.

In my local computer, I am using `D:/portable_tools` to install all the portable executables. You can tweak the directory to what you want. It is just what works for me.

> 4. I think the last line of the automated script should be:
scoop install neovim-nightly
since the comment above it talks about the nightly version

Yeah, previously I use neovim nightly, but now I stick to stable version to reduce breakage. So the code works, but the comment should be changed to reflect the new status.

> 5. would it be possible to install Packer and your config in the script so everything is installed in one go?

Yeah, it is definitely doable, like what I have done for Linux, but I have no time for now and my skill for powershell is also mediocre. The windows script is merely used to remind me of the steps that I can automate setting up nvim a bit. If you can automate it further, I would like to accept a PR for this.
