### ISSUE TITLE
yanking/autosave/LeaderF do not work

### ISSUE THREAD

**Issue by jahanbani** [jdhao/nvim-config#19]
Hi,
When I use the latest version of the config, `yy` or `y <motion>` does not work (`Y` works though). I am on Windows and use Nvy.

Also, I noticed that the autosave plug-in does not work, i.e. when I make a change to a buffer, even after exiting the insert mode, the buffer is not saved.

When invoking LeaderF (comma+f) I get the error of Not an editor command: LeaderF file --popup
There are more plugins that don't work so of course I am doing something terribly wrong; I am having the same issues on different machines that I tried this configuration; the `checkhealth` doesn't show any errors though.

I do not have these issues in your previous versions of the config file.  I have installed all of the requirements from the docs page.

Any help is appreciated.

**Comment by jdhao** [comment]
which version of nvim are you using?

**Comment by jahanbani** [comment]
nvim: 0.6.0
system: Windows 10

**Comment by jdhao** [comment]
@jahanbani  Which version of nvim are you using？I am also using nvim v0.6.0-dev+182-ga373ca1d8, and it works for me without any errors.

I suspect it has something to do with your settings. Some of the plugins can not be loaded properly due to your settings.

Are you sure you are using this config without any modification?

**Comment by jahanbani** [comment]
Yes, I am not modifying anything. I simply clone the configuration (as you wrote in docs). My nvim version is the latest as you have it.
I'll re-do the process again right now. Could it be that I needed to delete something after moving from the older version of the config?

**Comment by jahanbani** [comment]
I think I found the problem. On PowerShell the execution policy was restricted. I changed it to remote and recloned the configuration, and now it is working. Two other issues (especially the first):
1) I constantly get the following error when opening Python files:
![image](https://user-images.githubusercontent.com/16143553/135745921-448f13ed-3618-443b-840e-18b07c3106b3.png)

2) Some of the icons are not shown properly
![image](https://user-images.githubusercontent.com/16143553/135745960-83ea2f95-a878-46ce-8dce-83774e8f1643.png)

**Comment by jdhao** [comment]
> I constantly get the following error when doing autocomplete or from time to time; since it requires pressing enter (or escape) it is very annoying :(

It may be due to the latest change in Nvim. Nvim nightly introduces some breaking changes now and then, and I haven't had the time to track all of them. Are you using the latest nightly version of Nvim? 

Try the nvim 0.5 version to see if the error persists.

> Some of the icons are not shown properly

It has something to do with your `guifont` settings. Try to use one of the [nerd fonts](https://www.nerdfonts.com/).

**Comment by jahanbani** [comment]
I tried 0.5 version but the error is appearing even more frequently so I reverted to 0.6. When (if) you ever get to solve this, I'd appreciate it if you could share it.

I tried a few nerd fonts but the icons never showed up; I also tried fvim and it didn't help.

I have a few suggestions:
In your config, you don't install tree-sitter for windows, but on treesitter github, they explain that with clangd one could install treesitter on windows. Maybe you could consider this (since there are many plugins that rely on treesitter).

I wanted to add my own settings in another file, but I didn't know how to add my own plugins without having to modify your `plugins.lua` file. I think if an explanation is added in docs, it would be helpful for everyone who wants to use your config, and add a few more plugins or mappings

Thank you for your help. If I ever solve any of these, I will post them here.

**Comment by jdhao** [comment]
> I forgot to mention this error (which is persistent after reverting to 0.50 version), which happens when I have a (non-Python) file open and then I open a Python file.

The semshi issue is due to the lazyloading feature of packer, see [issue here](https://github.com/wbthomason/packer.nvim/issues/464). A workaround is to remove conditional loading for semshi and make semshi always load:

```
      use({ "numirias/semshi", config = "vim.cmd [[UpdateRemotePlugins]]" })
```

> In your config, you don't install treesitter for windows

Currently treesitter installation requires a C++ compiler which is missing on Windows. Since I mainly use neovim on Windows and Windows is notoriously unfriendly for development, I have no desire to install treesitter on Windows. If you want to do it, just follow the treesitter guide on how to use it on Windows.

> I wanted to add my own settings in another file, but I didn't know how to add my own plugins without having to modify your plugins.lua file.

If you want to add additional plugins, just modify `plugins.lua` and add your plugins, that is where all plugins are installed and managed by packer.

> when doing autocomplete, I don't get the list of function arguments.

This is the default behavior of nvim-lsp, you need to install other plugins to get what you want, for example, [lsp-signature](https://github.com/ray-x/lsp_signature.nvim). I have tried it and it does not work very reliably. You may give it a try to see if it works for you.

> Spell checker (maybe this) would be a good addition to the list of your plugins.

The nvim built-in spell checking is enough for me (toggled by pressing `F11`). I have no intention to install another plugin for now.

**Comment by jahanbani** [comment]
Thank you @jdhao  for your responses. I will close this issue now. I hope the error with neovim 0.6 is resolved soon; until then I will use 0.5 version. Thank you for your help :)

**Comment by jahanbani** [comment]
> > I forgot to mention this error (which is persistent after reverting to 0.50 version), which happens when I have a (non-Python) file open and then I open a Python file.
> 
> The semshi issue is due to the lazyloading feature of packer, see [issue here](https://github.com/wbthomason/packer.nvim/issues/464). A workaround is to remove conditional loading for semshi and make semshi always load:
> 
> ```
>       use({ "numirias/semshi", config = "vim.cmd [[UpdateRemotePlugins]]" })
> ```
> 
> > In your config, you don't install treesitter for windows
> 
> Currently treesitter installation requires a C++ compiler which is missing on Windows. Since I mainly use neovim on Linux and Windows is notoriously unfriendly for development, I have no desire to install treesitter on Windows. If you want to do it, just follow the treesitter guide on how to use it on Windows.
> 
> > I wanted to add my own settings in another file, but I didn't know how to add my own plugins without having to modify your plugins.lua file.
> 
> If you want to add additional plugins, just modify `plugins.lua` and add your plugins, that is where all plugins are installed and managed by packer.
> 
> > when doing autocomplete, I don't get the list of function arguments.
> 
> This is the default behavior of nvim-lsp, you need to install other plugins to get what you want, for example, [lsp-signature](https://github.com/ray-x/lsp_signature.nvim). I have tried it and it does not work very reliably. You may give it a try to see if it works for you.
> 
> > Spell checker (maybe this) would be a good addition to the list of your plugins.
> 
> The nvim built-in spell checking is enough for me (toggled by pressing `F11`) and it does not require additional plugins. I have no intention to install another plugin for now.

Hi,
Were you able to get the lsp-signature to work? I can't get it to work. It would be a good addition to your list of plugins.

**Comment by jdhao** [comment]
Sorry, I have no intention to support lsp-siganature for now.
