### ISSUE TITLE
LuaSnips on jdhao/nvim-config

### ISSUE THREAD

**Issue by Herk2** [jdhao/nvim-config#196]
I have just started experimenting with your vim-config and would like to know if it’s possible to work with LuaSnips, in addition to UltiSnips, in your nvim-config.

**Comment by jdhao** [comment]
do you want to use LuaSnips together with Ultisnips or only LuaSnips?

If together, I do not think it makes sense. If you only want to LuaSnip, just install it and uninstall Ultisnips. You also to need to adjust nvim-cmp settings, since it has configs related to snippet plugin (see [here](https://github.com/jdhao/nvim-config/blob/6c873a32da5410b6accbe8da476e334e2918901f/lua/config/nvim-cmp.lua#L6))

**Comment by Herk2** [comment]
I would like to do both together - to compare & contrast and get a better understanding thereby.  However, I don’t have to do both on the same device.  I can do Ultisnips on my MacVim and LuaSnips with your vim-config.

Thank you very much for your help and the heads up to the nvim-cmp settings adjustment issue.

Best wishes.

Herk

**Comment by jdhao** [comment]
if you want to do both, then you need to use if else condition for the install (in plugins.lua) and also for cmp config. It is not hard to adjust if you know a little bit lua.
