### ISSUE TITLE
Error when starting neovim using latest repo

### ISSUE THREAD

**Issue by jahanbani** [jdhao/nvim-config#27]
Hello,
When I use the latest version of the repo, on every start, I get the following error:
![image](https://user-images.githubusercontent.com/16143553/141154079-94f33054-e8b8-4a0e-8cef-27fe7f3d425a.png)
I am using v0.6-dev (and the same error occurs for other versions too), on Windows 11. Python is already in the path; `checkhealth` shows `treesitter` error (which is probably expected since `treesitter` plugin is not installed on windows in the plugins.

![image](https://user-images.githubusercontent.com/16143553/141154475-0ea7552f-a5ba-4c0c-bde3-3f0dc2ade2eb.png)

I was wondering if  you could shed some light on this issue.

**Comment by jdhao** [comment]
@jahanbani   This config is now tested against nvim 0.5.1, it probably won' work for nvim 0.6 since nvim 0.6 is undergoing large refactoring (I am tired of keeping up to date with master nvim now 😿 ).

Also in commit 2a0a92f134ac0a9a7db790d3639130a6b5a16823, I changed the location of `packer_compile.lua` generated by packer. You should delete `plugin/packer_compiled.lua` under your nvim config directory. After that, restart nvim and run command `PackerUpdate` and `PackerCompile`. Restart nvim and you should be good to go.

**Comment by jdhao** [comment]
@jahanbani I saw that you have opened several issues on this repo. So you are a long-time user of this config? 😃

**Comment by jahanbani** [comment]
Yes, and I have an itch for trying out your updates as you push them, so my config breaks all the time 😉 Apologies for asking too many questions 😄  
I like your configuration as your shortcuts mostly match what I would select (it could be because I am used to your config so I have developed the same "taste" as you in key mappings) and you actively add (the best of) useful plugins (I have another itch for the latest and best plugins too 😉).

**Comment by jdhao** [comment]
Thanks for trying my config.

The users should read the doc of plugins before using it. And this config serves as a inspiration for other nvim users and it is not intended to be used without knowing what you are doing. There are many things that may break.
