### ISSUE TITLE
vimtex ?

### ISSUE THREAD

**Issue by cadens07** [jdhao/nvim-config#4]
Hi !
Thanks for your config !

I'm trying to get vimtex working.
How to compile and previewing from your configs?
thanks

**Comment by jdhao** [comment]
What is your operating system and what is your neovim version? What has gone wrong?

For setting up vimtex, see also this [post](https://jdhao.github.io/2019/03/26/nvim_latex_write_preview/).

**Comment by cadens07** [comment]
I'm running config under arch linux.

here --> https://github.com/lervag/vimtex <-- the command \ll  \lv   \lk and \le working.
What's the equivalent under your configs tu use vimtex ?

regards

**Comment by jdhao** [comment]
I do not have a linux machine on my side, so I can not test this config under Linux. In this config, I have explicitly disable vimtex on Linux, see the relevant part [here](https://github.com/jdhao/nvim-config/blob/master/plugins.vim#L271). So if you want to use my config, you need to remove the if and endif block.

I haven't set any mappings (`\ll`, `\lv` etc.) for vimtex commands. So I just manually run `:VimtexCompile` and other commands to compile my LaTeX source file.

Also, since I do not have Linux machine, I only set up automatic viewing of the compiled PDF on Windows and Mac. If you want to do that on Linux, I am afraid you have to consult the vimtex documentation. But the configuration should be similar to that of Windows. The viewer settings of my config can be found [here](https://github.com/jdhao/nvim-config/blob/master/plugins.vim#L748).

I am currently using vim-plug to install plugins, to add a plugin, you just provide the plugin GitHub repo name like the following:

```vim
Plug 'user/repo_name'
```

For more info on how to use vim-plug, please consult the [official doc](https://github.com/junegunn/vim-plug).

**Comment by cadens07** [comment]
Ok! I Understand, from the beggiining vimtex is not installed (you mentionned "if windows or mac").
I follow yuor instruction --> Plug 'lervag/vimtex
WOrking now! 

thanks
