### ISSUE TITLE
file exploring

### ISSUE THREAD

**Issue by jahanbani** [jdhao/nvim-config#9]
Thank you for sharing your settings. I was wondering what you use for file browsing. Previous versions had `nerdtree` for this purpose, however, I noticed that you have removed this plugin in the latest version. (Windows 10, fvim)
Thank you

**Comment by jdhao** [comment]
yes, I use nerdtree for some time. I find I rarely use it and it is also slow for large directory, so I removed it. I use leaderf to open a project file, which works great for me.

If you really need a file explorer, nerdtree may not be the best option now, you may try fern.vim, vim-dirvish or other high performance alternatives.

**Comment by jahanbani** [comment]
Thank you for the response. What's your take on `kyazdani42/nvim-tree.lua`?
Thanks

**Comment by jdhao** [comment]
Personally, I think cross-platform support (Linux, macOS, Windows) is a must for such file exploring plugins. Features provided are also important: users should be able to do deleting, creating, and other common operations. High performance (in terms of speed) is a plus for such plugins.

I haven't tried it personally. Judging from its documentation, I can see several points:

+ platform: macOS, Linux, Windows
+ feature: seems complete
+ speed: havn't tried, but may be fast due to lua implementation?

**Comment by jdhao** [comment]
Actually, I have been planning to write a post to summarize all major file explorers for vim or nvim. I haven't finished it yet. Here is what I have got so far. I think you might be interested:

1. nerdtree: https://github.com/preservim/nerdtree

+ vim or Neovim: both
+ platform: Windows, Linux, macOS
+ feature: rich feature with a lot of mappings
+ speed: slow for large directory

2. fern.vim

3. vim-dirvish: https://github.com/justinmk/vim-dirvish

+ vim or nvim: both
+ platform: Windows, Linux, macOS
+ feature:  not very rich, concise without many decoration
+ speed: 

4. nvim-tree.lua: https://github.com/kyazdani42/nvim-tree.lua

+ vim or nvim: nvim only
+ platform: macOS, Linux, Windows
+ feature: seems complete
+ speed: havn't tried, but may be fast due to lua implementation?

5. tree.nvim: https://github.com/zgpio/tree.nvim

+ vim or nvim: nvim 
+ platform: Linux, macOS (author claims to support Windows, but no install script available)
+ feature: medium feature
+ speed: haven't tried. written in C++, maybe very fast

6. defx.nvim: https://github.com/Shougo/defx.nvim

+ vim or nvim: both
+ platform: Linux, macOS and Windows
+ feature: very rich
+ speed: haven't tried, but may be fast due to python implementation.

**Comment by jahanbani** [comment]
Thank you very much for your complete response.  I will try some of these file explorers. Appreciate your help and thank you for sharing your files :)
